name: malina_delivery
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8
  # di
  get_it: ^8.0.0
  dartz: ^0.10.1
  formz: ^0.7.0
  # keyboard dismiss
  flutter_keyboard_visibility: ^6.0.0
  # state manager bloc
  flutter_bloc: ^8.1.6
  # equations
  equatable: ^2.0.5
  # cache hive
  hive: ^2.2.3
  path_provider: ^2.1.3
  # native splash
  flutter_native_splash: ^2.4.1
  #flutter_svg:
  flutter_svg: ^2.0.10+1
  qr_code_scanner:
    git:
      url: https://github.com/SunnatilloShavkatov/qr_code_scanner.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_intl:
  enabled: true
  class_name: AppLocalization
  arb-dir: lib/localization/l10n
  preferred-supported-locales:
    - ru
  use-deferred-loading: true